[build]
  base = "frontend/"
  publish = "build/"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"